name: Update patrons.json

on:
  schedule:
    # | minute | hour | day of month | month of year | day of week | (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
    # every day at 3:45 AM UTC (arbitrarily chosen)
    - cron: '45 3 * * *'
  workflow_dispatch:

jobs:
  schedule-patrons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Hash patrons.json pre-edit
        id: patrons_hash_pre
        run: |
            echo ::set-output name=HASH::"${{hashFiles('./files/patrons.json')}}"

      - name: Pip install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch.py
        run: python fetch.py ${{secrets.PATREON_TOKEN}} ${{secrets.DISCORD_BOT_TOKEN}} ${{secrets.DISCORD_APPID}}

      - name: Hash patrons.json post-edit
        id: patrons_hash_post
        run: echo ::set-output name=HASH::"${{hashFiles('./files/patrons.json')}}"

      - name: Upload patrons artifact
        uses: actions/upload-artifact@v2
        with:
          name: patrons.json
          path: './files/patrons.json'
          if-no-files-found: error

      # only execute if the hashes are different
      - name: Configure commit
        if: ${{ steps.patrons_hash_pre.outputs.HASH != steps.patrons_hash_post.outputs.HASH }}
        run: |
          git config user.name "Github Actions"
          git config user.email "<>"

      # only execute if the hashes are different
      - name: Commit & push patrons.json
        if: ${{ steps.patrons_hash_pre.outputs.HASH != steps.patrons_hash_post.outputs.HASH }}
        run: |
          git add './files/patrons.json'
          git commit -m "Updated patrons.json"
          git push
